[workspace]
resolver = "2"
members = [
  "alkaline",
  "alk", "alkaline_markdown_adapter",
]


[workspace.dependencies]
anyhow = "1.0"
chrono = "0.4"
thiserror = "1.0"
tracing = "0.1"
async-trait = "0.1"
tokio = "1.36"
serde = "1.0"
serde_json = "1.0"
ron = "0.8"
